# Generated by Django 3.1 on 2020-09-07 00:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='GameNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 7, 10, 23, 55, 623200))),
                ('current_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homePage.userdetails')),
                ('user_game', models.ManyToManyField(blank=True, related_name='game', to='homePage.UserDetails')),
            ],
        ),
    ]
