# Generated by Django 3.1 on 2020-09-07 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_auto_20200907_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamenumber',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 10, 44, 48, 226184)),
        ),
        migrations.RemoveField(
            model_name='gamenumber',
            name='user_game',
        ),
        migrations.AddField(
            model_name='gamenumber',
            name='user_game',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
