# Generated by Django 3.1 on 2020-09-07 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_auto_20200907_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamenumber',
            name='game_week',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gamenumber',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gamenumber',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 10, 50, 25, 798546)),
        ),
    ]
